"""create bank transactions table

Revision ID: 0d99571bf88b
Revises: 260f05667c21
Create Date: 2026-05-12 19:21:03.045791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d99571bf88b'
down_revision: Union[str, Sequence[str], None] = '260f05667c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('data_transacao', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('identificador_externo', sa.String(), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
