"""add hash transaction

Revision ID: 502d5f1a072b
Revises: 73e8267348be
Create Date: 2026-05-12 19:32:14.191940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502d5f1a072b'
down_revision: Union[str, Sequence[str], None] = '73e8267348be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('hash_transacao', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'bank_transactions', ['hash_transacao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='unique')
    op.drop_column('bank_transactions', 'hash_transacao')
    # ### end Alembic commands ###
