"""create bank reconciliations table

Revision ID: 73e8267348be
Revises: 0d99571bf88b
Create Date: 2026-05-12 19:25:18.745784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e8267348be'
down_revision: Union[str, Sequence[str], None] = '0d99571bf88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('accounts_payable_id', sa.UUID(), nullable=True),
    sa.Column('accounts_receivable_id', sa.UUID(), nullable=True),
    sa.Column('valor_conciliado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_conciliacao', sa.Date(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accounts_payable_id'], ['accounts_payable.id'], ),
    sa.ForeignKeyConstraint(['accounts_receivable_id'], ['accounts_receivable.id'], ),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_reconciliations')
    # ### end Alembic commands ###
